### ISSUE TITLE
Timeouts in Julia 1.7.2 (due to ` setopt(easy, CURLOPT_LOW_SPEED_TIME, 20)` in new Downloads.jl)

### ISSUE THREAD

**Issue by manuelbb-upb** [JuliaComputing/gRPCClient.jl#22]
After upgrading from Julia 1.6.1 to Julia 1.7.2, I noticed that some of my requests would fail with 
```
gRPCServiceCallException: 4, Deadline expired before the operation could complete
```
for tasks with a long response time.
The error persisted for any combination of `request_timeout` and `connection_timeout` values.
Setting `maxage` did completely stall everything.

I believe that the error is due to a version jump of the "Downloads" package.
In my case it went from 1.4.0 to 1.5.2.
I think [this line](https://github.com/JuliaLang/Downloads.jl/blob/9f738d30e1256a4c122dff9f38536cfc1feeca8e/src/Curl/Easy.jl#L62) is responsible, which sets 
```julia 
setopt(easy, CURLOPT_LOW_SPEED_TIME, 20)
```
This seems to be due to https://github.com/JuliaLang/Downloads.jl/pull/126 which was merged into all versions of Downloads >= 1.4.1.

I have put 
```julia
Curl.setopt(easy, CURLOPT_LOW_SPEED_TIME, Clong(0))
```
at the beginning of `set_connect_timeout()` in src/curl.jl and the error is gone.

So as a fix I would propose to expose the option as an additional keyword argument, i.e., `low_speed_time`, with a default value of 0.

**Comment by tanmaykm** [comment]
There were existing tests for request timeout handling. There's now a [test](https://github.com/JuliaComputing/gRPCClient.jl/pull/30) for connect timeouts, which runs successfully.

Actually from CURL docs it seems that the default value of [`CURLOPT_LOW_SPEED_TIME`](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html) and [`CURLOPT_LOW_SPEED_LIMIT`](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html) are `0`, meaning that they are disabled. So the only timeout that should be effective is the `request_timeout` (and `connection_timeout` if connect is slow). So looks like it is not necessary to specify these to get the behavior we need.

I believe the actual issue here was something else, most likely what got fixed by https://github.com/JuliaComputing/gRPCClient.jl/pull/26
